apiVersion: v1
entries:
  sample-nginx:
  - apiVersion: v2
    appVersion: "1"
    created: "2021-05-27T15:06:49.578178-04:00"
    description: my custom nginx chart
    digest: b25bae7068d125ca230f7a7fbc244a466e4cc866632f6d20f3c0ff2b0c8bbd73
    name: sample-nginx
    urls:
    - sample-nginx-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: "1"
    created: "2021-05-27T15:06:49.577982-04:00"
    description: my custom nginx chart
    digest: cad7c3bf873c167807a3cd1fd70becdc052899f0ec1f3c50492cd98ddb61d8d0
    name: sample-nginx
    urls:
    - sample-nginx-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: "1"
    created: "2021-05-27T15:06:49.577397-04:00"
    description: my custom nginx chart
    digest: 52233e9cbecec2ed26e1b13bc76dad7d442b87cc4041d208e5cc1f8670e0bc6e
    name: sample-nginx
    urls:
    - sample-nginx-0.1.0.tgz
    version: 0.1.0
generated: "2021-05-27T15:06:49.576693-04:00"
