apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - image: repository.intranet.roche.com:6563/com.gene.bioinfo.ms/2048demo:latest
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80